version: '3.8'

services:
  wallbox-reporter:
    image: python:3.12-slim
    working_dir: /app
    command: >
      bash -c "
      apt-get update && 
      apt-get install -y git &&
      git clone https://github.com/anlx-sw/loxone-wallbox-reporter.git /tmp/repo &&
      cp /tmp/repo/* /app/ &&
      rm -rf /tmp/repo &&
      pip install --no-cache-dir -r requirements.txt &&
      python wallbox_reporter.py"
    environment:
      - FTP_SERVER=loxone-miniserver.local
      - FTP_USER=meinbenutzer
      - FTP_PASSWORD=meinpasswort
      - FILTER_USER=AZ999ZZ
      - SMTP_SERVER=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USER=your-email@example.com
      - SMTP_PASSWORD=your-password
      - BILLING_EMAIL=billing@example.com
      - ADMIN_EMAIL=admin@example.com
    volumes:
      - wallbox_reports:/app/reports
    restart: unless-stopped

volumes:
  wallbox_reports: